### ISSUE TITLE
I have troubles using your config with TypeScript

### ISSUE THREAD

**Issue by romap0** [monke-systems/monke-eslint-config#2]
I have added your config to my project and received this error:
```
ESLint: 8.57.0

Error: Error while loading rule '@typescript-eslint/await-thenable': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
```

To fix this issue I needed to update my config this way:

```
parserOptions:
  project: ./tsconfig.json
```

Could you please add it to project readme?

**Comment by Enity** [comment]
done in https://github.com/monke-systems/monke-eslint-config/commit/af5066a75bcc50db3f06f89e25a7026cccd82824
thanks!

**Comment by Enity** [comment]
done in https://github.com/monke-systems/monke-eslint-config/commit/af5066a75bcc50db3f06f89e25a7026cccd82824
thanks!
